In [1]:
import readingtxt

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [2]:
readingtxt.run()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [3]:
import readingtxt

In [4]:
readingtxt.run()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [5]:
exit()

In [1]:
import readingtxt

Data Frame

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [2]:
exit()

In [1]:
import radingtxt

ModuleNotFoundError: No module named 'radingtxt'

import readingtxt

In [2]:
import readingtxt

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (readingtxt.py, line 16)

In [3]:
exit()

In [1]:
import readingtxt

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (readingtxt.py, line 16)

In [2]:
exit()

In [1]:
import readingtxt

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (readingtxt.py, line 15)

In [2]:
exit()

In [1]:
import readingtxt

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (readingtxt.py, line 15)

In [2]:
exit()

In [1]:
import readingtxt

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (readingtxt.py, line 15)

In [2]:
exit()

In [1]:
import readingtxt

Data Frame 1:

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

FileNotFoundError: File b'C:/Users/user/desktop/GDRIVETEMP/WIP/Filesharing/Physics_development_02Jan_to_28_Feb_2018.csv' does not exist

In [1]:
exit()

In [1]:
import readingtxt

Data Frame 1:

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

Data Frame 2:

,Unnamed: 0,Unnamed: 1,DEVELOPMENT_DURATION = ????,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,SUBJECT: PHYSICS_O_level,NaN,NaN,NaN
1,NAME,SURNAME,TOPIC,SUBTOPIC,DURATION/DAYS,WEEK-ENDING
2,Daniel Murati,Nkomo,2.0 Electricity,2.1 Electrostatics,NaN,NaN
3,NaN,NaN,NaN,2.2 Primary & secondary cells,NaN,NaN
4,NaN,NaN,NaN,2.3 Current electricity,NaN,NaN

In [2]:
exit()

In [1]:
import readingtxt

Data Frame 1:

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

Data Frame 2:

,Unnamed: 0,Unnamed: 1,DEVELOPMENT_DURATION = ????,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,SUBJECT: PHYSICS_O_level,NaN,NaN,NaN
1,NAME,SURNAME,TOPIC,SUBTOPIC,DURATION/DAYS,WEEK-ENDING
2,Daniel Murati,Nkomo,2.0 Electricity,2.1 Electrostatics,NaN,NaN
3,NaN,NaN,NaN,2.2 Primary & secondary cells,NaN,NaN
4,NaN,NaN,NaN,2.3 Current electricity,NaN,NaN
5,NaN,NaN,NaN,2.4 Electric circuits,NaN,NaN
6,NaN,NaN,NaN,2.5 Electricity in the home,NaN,NaN
7,NaN,NaN,NaN,2.0 Test,NaN,NaN
8,NaN,NaN,4.0 Electro-magnetism,4.2 Force on current carrying conductor,NaN,NaN
9,NaN,NaN,NaN,4.0 Test,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,Tapiwa Lawrence,Konga,1.0 Optics,1.1 Reflection of light,NaN,NaN
12,NaN,NaN,NaN,1.2 Refraction of light,NaN,NaN
13,NaN,NaN,NaN,1.3 Lenses,NaN,NaN
14,NaN,NaN,NaN,1.4 Dispersion of light,NaN,NaN
15,NaN,NaN,NaN,1.0 Test,NaN,NaN
16,NaN,NaN,5.0 Electronics,5.1 Thermionic emmision,NaN,NaN
17,NaN,NaN,NaN,5.2 diodes,NaN,NaN
18,NaN,NaN,NaN,5.3 Rectification,NaN,NaN
19,NaN,NaN,NaN,5.4 Electronic components,NaN,NaN
20,NaN,NaN,NaN,5.5 Logic Gates,NaN,NaN
21,NaN,NaN,NaN,5.0 Test,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,Mduduzi Frederick,Dube,3.0 Magnetism,3.1 Magnetic properties,NaN,NaN
24,NaN,NaN,NaN,3.2 Application of magetism,NaN,NaN
25,NaN,NaN,NaN,3.0 Test,NaN,NaN
26,NaN,NaN,4.0 Electromagnetism,4.1 Magnetic effect of an electric current,NaN,NaN
27,NaN,NaN,NaN,4.3 Electromagetic induction,NaN,NaN
28,NaN,NaN,NaN,4.4 Transformers,NaN,NaN
29,NaN,NaN,6.0 Atomic and nuclear physics,6.1 Rutherford's Atomic model,NaN,NaN
30,NaN,NaN,NaN,6.2 Radioactivity,NaN,NaN
31,NaN,NaN,NaN,6.0 Test,NaN,NaN

In [2]:
exit()

In [1]:
import raedingtxt

ModuleNotFoundError: No module named 'raedingtxt'

In [2]:
import readingtxt

Data Frame 1:

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

AttributeError: 'function' object has no attribute 'data_1'

In [3]:
exit()

In [1]:
import readtingtx

ModuleNotFoundError: No module named 'readtingtx'

In [2]:
import readingtxt

Data Frame 1:

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

array(['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan",
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls',
       'Intl Charge', 'CustServ Calls', 'Churn?'], dtype=object)

Data Frame 2:

,Unnamed: 0,Unnamed: 1,DEVELOPMENT_DURATION = ????,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,SUBJECT: PHYSICS_O_level,NaN,NaN,NaN
1,NAME,SURNAME,TOPIC,SUBTOPIC,DURATION/DAYS,WEEK-ENDING
2,Daniel Murati,Nkomo,2.0 Electricity,2.1 Electrostatics,NaN,NaN
3,NaN,NaN,NaN,2.2 Primary & secondary cells,NaN,NaN
4,NaN,NaN,NaN,2.3 Current electricity,NaN,NaN
5,NaN,NaN,NaN,2.4 Electric circuits,NaN,NaN
6,NaN,NaN,NaN,2.5 Electricity in the home,NaN,NaN
7,NaN,NaN,NaN,2.0 Test,NaN,NaN
8,NaN,NaN,4.0 Electro-magnetism,4.2 Force on current carrying conductor,NaN,NaN
9,NaN,NaN,NaN,4.0 Test,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,Tapiwa Lawrence,Konga,1.0 Optics,1.1 Reflection of light,NaN,NaN
12,NaN,NaN,NaN,1.2 Refraction of light,NaN,NaN
13,NaN,NaN,NaN,1.3 Lenses,NaN,NaN
14,NaN,NaN,NaN,1.4 Dispersion of light,NaN,NaN
15,NaN,NaN,NaN,1.0 Test,NaN,NaN
16,NaN,NaN,5.0 Electronics,5.1 Thermionic emmision,NaN,NaN
17,NaN,NaN,NaN,5.2 diodes,NaN,NaN
18,NaN,NaN,NaN,5.3 Rectification,NaN,NaN
19,NaN,NaN,NaN,5.4 Electronic components,NaN,NaN
20,NaN,NaN,NaN,5.5 Logic Gates,NaN,NaN
21,NaN,NaN,NaN,5.0 Test,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,Mduduzi Frederick,Dube,3.0 Magnetism,3.1 Magnetic properties,NaN,NaN
24,NaN,NaN,NaN,3.2 Application of magetism,NaN,NaN
25,NaN,NaN,NaN,3.0 Test,NaN,NaN
26,NaN,NaN,4.0 Electromagnetism,4.1 Magnetic effect of an electric current,NaN,NaN
27,NaN,NaN,NaN,4.3 Electromagetic induction,NaN,NaN
28,NaN,NaN,NaN,4.4 Transformers,NaN,NaN
29,NaN,NaN,6.0 Atomic and nuclear physics,6.1 Rutherford's Atomic model,NaN,NaN
30,NaN,NaN,NaN,6.2 Radioactivity,NaN,NaN
31,NaN,NaN,NaN,6.0 Test,NaN,NaN